# Generated by Django 4.2.4 on 2023-09-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('mobilenumber', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('area', models.CharField(max_length=220)),
            ],
        ),
    ]
